name: Go
on: [push]

env:
  GOGC: 50

jobs:
  build:
    runs-on: arc-runner-set-errorsis
    strategy:
      matrix:
        os: [ 'freebsd', 'linux']
        arch: [ 'amd64', 'arm64']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: |
          go get ./cmd/...
      - name: Build
        run: |
          export GOOS=${{ matrix.os }}
          export GOARCH=${{ matrix.arch }}
          go build -o errorsis ./cmd/errorsis
      - name: Build Plugin
        run: |
          export GOOS=${{ matrix.os }}
          export GOARCH=${{ matrix.arch }}
          go build -buildmode=plugin plugin/errorsis.go