name: Go
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

env:
  GOGC: 50

jobs:
  build:
    runs-on: arc-runner-set-errorsis
    strategy:
      matrix:
        os: [ 'freebsd', 'linux', 'darwin']
        arch: [ 'amd64', 'arm64']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: |
          go get ./cmd/...
      - name: Build standalone
        run: |
          export GOOS=${{ matrix.os }}
          export GOARCH=${{ matrix.arch }}
          go build -o errorsis ./cmd/errorsis
