name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  GOGC: 50

jobs:
  golangci:
    name: lint
    runs-on: arc-runner-set-errorsis
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: |
          go get ./cmd/...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
          args: --timeout=60m
