name: Go
on: [push]

env:
  GOGC: 50

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          - freebsd-amd64
          - freebsd-arm64
          - linux-amd64
          - linux-arm64
          - darwin-amd64
          - darwin-arm64
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: |
          go get ./cmd/...
      - name: Build plugin
        uses: go-cross/cgo-actions@v1
        with:
          flags: "-buildmode=plugin"
          packages: plugin/errorsis.go
          targets: ${{ matrix.targets }}
